// Same column order as profile.ts. Only interface copy, never personal values.
export const ONBOARDING_ROWS = `
Читайте то, что полезно именно вам|Read what matters to you|Lies, was dir wirklich hilft|Lee lo que te resulte útil|Lisez ce qui vous est utile|Leggi ciò che ti è utile|阅读真正对你有用的内容|اقرأ ما يفيدك أنت|वही पढ़ें जो आपके काम आए
Attention помогает решить, стоит ли открывать статью, и найти в ней фрагменты, которые могут дать вам что-то новое.|Attention helps you decide whether to open an article and find passages that could teach you something new.|Attention hilft dir zu entscheiden, ob sich ein Artikel lohnt, und Textstellen zu finden, aus denen du etwas Neues lernen kannst.|Attention te ayuda a decidir si merece la pena abrir un artículo y a encontrar pasajes que puedan aportarte algo nuevo.|Attention vous aide à décider si un article mérite d’être ouvert et à y trouver des passages qui pourraient vous apprendre quelque chose.|Attention ti aiuta a decidere se vale la pena aprire un articolo e a trovare passaggi da cui potresti imparare qualcosa di nuovo.|Attention 帮你判断文章是否值得打开，并找到可能带来新知识的片段。|يساعدك Attention على تحديد ما إذا كان المقال يستحق فتحه، والعثور على مقاطع قد تتعلم منها شيئًا جديدًا.|Attention यह तय करने में मदद करता है कि कोई लेख खोलना उपयोगी होगा या नहीं, और उसमें ऐसे अंश ढूँढ़ता है जिनसे आप कुछ नया सीख सकें।
Для этого ему нужно немного узнать о вас:|To do that, it needs to know a little about you:|Dafür muss es ein wenig über dich wissen:|Para ello, necesita conocerte un poco:|Pour cela, il a besoin d’en savoir un peu sur vous :|Per farlo, deve conoscerti un po’:|为此，它需要先了解你：|ولذلك يحتاج إلى معرفة القليل عنك:|इसके लिए उसे आपके बारे में थोड़ा जानना होगा:
Что вам интересно и над чем вы работаете.|What interests you and what you’re working on.|Was dich interessiert und woran du arbeitest.|Qué te interesa y en qué estás trabajando.|Ce qui vous intéresse et ce sur quoi vous travaillez.|Cosa ti interessa e a cosa stai lavorando.|你感兴趣的主题和正在做的事。|ما يثير اهتمامك وما تعمل عليه.|आपकी रुचियाँ और आप किस पर काम कर रहे हैं।
В чём вы уже разбираетесь.|What you already know.|Womit du dich bereits auskennst.|Qué sabes ya.|Ce que vous connaissez déjà.|Cosa sai già.|你已经熟悉的领域。|ما تعرفه بالفعل.|आप पहले से क्या जानते हैं।
Без этого одна и та же рекомендация достанется и новичку, и специалисту.|Otherwise, a beginner and an expert get the same recommendation.|Sonst bekommen Einsteiger und Fachleute dieselbe Empfehlung.|Sin ese contexto, principiantes y expertos reciben la misma recomendación.|Sans cela, débutants et spécialistes reçoivent la même recommandation.|Senza queste informazioni, principianti ed esperti ricevono lo stesso consiglio.|否则，初学者和专家会得到相同的建议。|من دون ذلك، سيحصل المبتدئ والمتخصص على التوصية نفسها.|इसके बिना, शुरुआती और विशेषज्ञ दोनों को एक ही सुझाव मिलेगा।
Создать мой профиль|Create my profile|Mein Profil erstellen|Crear mi perfil|Créer mon profil|Crea il mio profilo|创建我的资料|أنشئ ملفي|मेरी प्रोफ़ाइल बनाएँ
Начните с ChatGPT или Claude: они помогут собрать ваши интересы, знания и цели в профиль для Attention.|Start with ChatGPT or Claude: they’ll help bring your interests, knowledge and goals together in a profile for Attention.|Beginne mit ChatGPT oder Claude: Sie helfen dir, deine Interessen, Kenntnisse und Ziele in einem Profil für Attention zusammenzufassen.|Empieza con ChatGPT o Claude: te ayudarán a reunir tus intereses, conocimientos y objetivos en un perfil para Attention.|Commencez avec ChatGPT ou Claude : ils vous aideront à réunir vos intérêts, connaissances et objectifs dans un profil pour Attention.|Inizia con ChatGPT o Claude: ti aiuteranno a raccogliere interessi, conoscenze e obiettivi in un profilo per Attention.|从 ChatGPT 或 Claude 开始：它们会帮你整理兴趣、知识和目标，生成用于 Attention 的个人资料。|ابدأ بـ ChatGPT أو Claude: سيساعدانك على جمع اهتماماتك ومعارفك وأهدافك في ملف لـ Attention.|ChatGPT या Claude से शुरू करें: वे आपकी रुचियों, ज्ञान और लक्ष्यों को Attention के लिए एक प्रोफ़ाइल में समेटने में मदद करेंगे।
Что стоит вашего времени?|What deserves your time?|Was ist deine Zeit wert?|¿Qué merece tu tiempo?|Qu’est-ce qui mérite votre temps ?|Cosa merita il tuo tempo?|什么值得你花时间？|ما الذي يستحق وقتك؟|आपके समय के लायक क्या है?
Attention помогает выбрать, что читать и на каких фрагментах остановиться.|Attention helps you choose what to read and which passages to focus on.|Attention hilft dir, Lesestoff und wichtige Textstellen auszuwählen.|Attention te ayuda a elegir qué leer y en qué pasajes detenerte.|Attention vous aide à choisir quoi lire et quels passages approfondir.|Attention ti aiuta a scegliere cosa leggere e su quali passaggi soffermarti.|Attention 帮你选择值得阅读的文章和片段。|يساعدك Attention على اختيار ما تقرأ والمقاطع التي تستحق التركيز.|Attention पढ़ने की सामग्री और ध्यान देने वाले अंश चुनने में मदद करता है।
Одна статья. Разный смысл для вас.|One article. Different value for you.|Ein Artikel. Unterschiedlicher Nutzen.|Un artículo. Distinto valor para ti.|Un article. Une utilité différente pour vous.|Un articolo. Un valore diverso per te.|同一篇文章，对你有不同价值。|مقال واحد، وقيمة مختلفة لك.|एक लेख। आपके लिए अलग उपयोगिता।
Учебный пример|Illustrative example|Anschauliches Beispiel|Ejemplo ilustrativo|Exemple illustratif|Esempio illustrativo|演示示例|مثال توضيحي|समझाने के लिए उदाहरण
Как оценивать ответы AI: первые шаги|Evaluating AI answers: getting started|KI-Antworten bewerten: erste Schritte|Evaluar respuestas de IA: primeros pasos|Évaluer les réponses de l’IA : premiers pas|Valutare le risposte AI: primi passi|如何评估 AI 回答：入门|تقييم إجابات الذكاء الاصطناعي: البداية|AI के जवाब परखना: शुरुआत
Я изучаю эту тему|I’m learning this topic|Ich lerne dieses Thema|Estoy aprendiendo este tema|Je découvre ce sujet|Sto imparando questo argomento|我正在学习这个主题|أتعلم هذا الموضوع|मैं यह विषय सीख रहा हूँ
Я уже знаю основы|I already know the basics|Ich kenne die Grundlagen|Ya conozco lo básico|Je connais déjà les bases|Conosco già le basi|我已了解基础知识|أعرف الأساسيات بالفعل|मुझे बुनियादी बातें आती हैं
Стоит прочитать|Worth reading|Lesenswert|Vale la pena leer|À lire|Vale la pena leggere|值得阅读|يستحق القراءة|पढ़ना उपयोगी होगा
Критерии и примеры помогут начать оценивать ответы моделей.|Criteria and examples will help you start evaluating model answers.|Kriterien und Beispiele helfen dir beim Einstieg in die Bewertung von Modellantworten.|Los criterios y ejemplos te ayudarán a empezar a evaluar respuestas.|Les critères et exemples vous aideront à commencer à évaluer les réponses.|Criteri ed esempi ti aiuteranno a iniziare a valutare le risposte.|标准和示例能帮助你开始评估模型回答。|تساعدك المعايير والأمثلة على بدء تقييم إجابات النماذج.|मानदंड और उदाहरण मॉडल के जवाब परखना शुरू करने में मदद करेंगे।
Основы можно пропустить|You can skip the basics|Die Grundlagen kannst du überspringen|Puedes saltarte lo básico|Vous pouvez passer les bases|Puoi saltare le basi|可以跳过基础内容|يمكنك تجاوز الأساسيات|बुनियादी बातें छोड़ सकते हैं
Начните с примера сложной ошибки — вводная часть вам уже знакома.|Start with the tricky error example — you already know the introduction.|Beginne mit dem Beispiel eines kniffligen Fehlers – die Einführung kennst du bereits.|Empieza por el ejemplo del error difícil: ya conoces la introducción.|Commencez par l’exemple d’erreur complexe : vous connaissez déjà l’introduction.|Inizia dall’esempio di errore difficile: conosci già l’introduzione.|从复杂错误的示例开始——入门部分你已熟悉。|ابدأ بمثال الخطأ المعقد، فالمقدمة مألوفة لك.|जटिल गलती के उदाहरण से शुरू करें — परिचय आप पहले से जानते हैं।
Чтобы советовать именно вам, Attention нужно немного вас узнать.|To make recommendations for you, Attention needs to get to know you.|Für persönliche Empfehlungen muss Attention dich etwas kennenlernen.|Para recomendarte lecturas, Attention necesita conocerte un poco.|Pour vous conseiller, Attention a besoin de vous connaître un peu.|Per consigliarti, Attention deve conoscerti un po’.|为了给你合适的建议，Attention 需要先了解你。|ليقدم Attention اقتراحات تناسبك، يحتاج إلى معرفتك قليلًا.|आपके लिए सुझाव देने के लिए Attention को आपको थोड़ा जानना होगा।
Настроить под меня|Make it personal|Auf mich abstimmen|Adaptarlo a mí|Personnaliser|Personalizza per me|为我设置|خصصه لي|मेरे लिए सेट करें
Кто уже знает ваши интересы?|Who already knows your interests?|Wer kennt deine Interessen schon?|¿Quién conoce ya tus intereses?|Qui connaît déjà vos intérêts ?|Chi conosce già i tuoi interessi?|谁已经了解你的兴趣？|من يعرف اهتماماتك بالفعل؟|आपकी रुचियों को कौन पहले से जानता है?
Выберите AI, с которым обсуждали работу, учёбу или увлечения. Он поможет собрать профиль из знакомого ему контекста. Второй можно добавить позже.|Choose the AI you’ve talked to about work, learning or hobbies. It can help build a profile from the context it knows. You can add another profile later.|Wähle die KI, mit der du über Arbeit, Lernen oder Hobbys gesprochen hast. Sie hilft mit dem Kontext, den sie kennt. Weitere Profile kannst du später ergänzen.|Elige la IA con la que hablas de trabajo, aprendizaje o aficiones. Te ayudará con el contexto que conoce. Puedes añadir otro perfil después.|Choisissez l’IA avec laquelle vous avez parlé de travail, d’études ou de loisirs. Elle utilisera le contexte qu’elle connaît. Vous pourrez ajouter un autre profil ensuite.|Scegli l’AI con cui hai parlato di lavoro, studio o hobby. Ti aiuterà con il contesto che conosce. Potrai aggiungere un altro profilo dopo.|选择聊过工作、学习或爱好的 AI。它能根据已有背景帮助整理资料，以后还可以添加另一个。|اختر الذكاء الاصطناعي الذي تحدثت معه عن العمل أو التعلم أو الهوايات. سيساعدك بالسياق الذي يعرفه، ويمكنك إضافة الآخر لاحقًا.|वह AI चुनें जिससे काम, पढ़ाई या शौक पर बात की है। वह परिचित संदर्भ से प्रोफ़ाइल बनाने में मदद करेगा। दूसरा बाद में जोड़ सकते हैं।
Я пока не пользуюсь ими|I don’t use these yet|Ich nutze diese Dienste noch nicht|Aún no uso estos servicios|Je n’utilise aucun de ces services|Non uso ancora questi servizi|我还没用过这些服务|لا أستخدم هذه الخدمات بعد|मैं अभी इन सेवाओं का उपयोग नहीं करता
Ответьте на несколько вопросов о своих задачах и опыте. Чем конкретнее примеры, тем полезнее рекомендации.|Answer a few questions about your goals and experience. Specific examples make recommendations more useful.|Beantworte einige Fragen zu Zielen und Erfahrung. Konkrete Beispiele machen Empfehlungen hilfreicher.|Responde unas preguntas sobre tus objetivos y experiencia. Los ejemplos concretos ayudan a recomendar mejor.|Répondez à quelques questions sur vos objectifs et votre expérience. Des exemples précis rendent les conseils plus utiles.|Rispondi a qualche domanda su obiettivi ed esperienza. Esempi concreti rendono i consigli più utili.|回答几个关于目标和经验的问题。示例越具体，建议越有用。|أجب عن أسئلة حول أهدافك وخبرتك. الأمثلة المحددة تجعل الاقتراحات أنفع.|लक्ष्यों और अनुभव के बारे में कुछ सवालों के जवाब दें। ठोस उदाहरण सुझावों को अधिक उपयोगी बनाते हैं।
Ответить на вопросы|Answer a few questions|Fragen beantworten|Responder preguntas|Répondre aux questions|Rispondi alle domande|回答问题|أجب عن الأسئلة|सवालों के जवाब दें
Скопируйте весь ответ и вставьте сюда.|Copy the whole answer and paste it here.|Kopiere die ganze Antwort hierher.|Copia toda la respuesta y pégala aquí.|Copiez toute la réponse et collez-la ici.|Copia tutta la risposta e incollala qui.|复制完整回答并粘贴到这里。|انسخ الإجابة كاملة والصقها هنا.|पूरा जवाब कॉपी करके यहाँ पेस्ट करें।
Ответ от AI|The AI’s answer|Antwort der KI|Respuesta de la IA|Réponse de l’IA|Risposta dell’AI|AI 的回答|إجابة الذكاء الاصطناعي|AI का जवाब
Вставьте ответ целиком — разберём его за вас.|Paste the whole answer — we’ll sort it out for you.|Füge die gesamte Antwort ein – wir bereiten sie auf.|Pega toda la respuesta: nosotros la organizamos.|Collez toute la réponse : nous la mettrons en forme.|Incolla tutta la risposta: la organizziamo noi.|粘贴完整回答，我们来整理。|الصق الإجابة كاملة وسنرتبها لك.|पूरा जवाब पेस्ट करें — हम उसे व्यवस्थित करेंगे।
Посмотреть мой профиль|Preview my profile|Mein Profil ansehen|Ver mi perfil|Voir mon profil|Vedi il mio profilo|查看我的资料|اعرض ملفي|मेरी प्रोफ़ाइल देखें
Всё верно?|Does this look right?|Stimmt das so?|¿Está todo bien?|Tout est correct ?|È tutto corretto?|这些信息准确吗？|هل هذا صحيح؟|क्या यह सही है?
Исправьте неточности или удалите лишнее. Эти сведения помогут выбирать чтение для вас.|Correct anything inaccurate or remove what doesn’t belong. This will guide your reading recommendations.|Korrigiere Ungenaues oder entferne Unpassendes. Diese Angaben helfen bei deinen Leseempfehlungen.|Corrige lo inexacto o elimina lo que sobra. Estos datos orientarán tus recomendaciones.|Corrigez les erreurs ou retirez le superflu. Ces informations guideront vos conseils de lecture.|Correggi le inesattezze o elimina ciò che non serve. Queste informazioni guideranno i consigli.|修正不准确的信息或删除多余内容，这些信息将用于推荐阅读。|صحح الأخطاء أو احذف ما لا يناسبك. ستوجه هذه المعلومات اقتراحات القراءة.|गलत बातें सुधारें या अनावश्यक जानकारी हटाएँ। यही पढ़ने के सुझावों का आधार बनेगी।
Сейчас мне важно|What matters to me now|Was mir gerade wichtig ist|Lo que me importa ahora|Ce qui compte pour moi maintenant|Cosa mi importa adesso|我目前关注的目标|ما يهمني الآن|अभी मेरे लिए ज़रूरी है
Мне интересно|I’m interested in|Mich interessiert|Me interesa|Ce qui m’intéresse|Mi interessa|我感兴趣的主题|ما يثير اهتمامي|मेरी रुचियाँ
Что я знаю и изучаю|What I know and am learning|Was ich weiß und lerne|Lo que sé y estoy aprendiendo|Ce que je sais et apprends|Cosa so e sto imparando|我知道什么、正在学习什么|ما أعرفه وما أتعلمه|मैं क्या जानता और सीख रहा हूँ
Все подробности профиля|All profile details|Alle Profildetails|Todos los detalles|Tous les détails du profil|Tutti i dettagli del profilo|全部资料详情|كل تفاصيل الملف|प्रोफ़ाइल की सभी जानकारी
Дополнить|Add more|Ergänzen|Añadir|Compléter|Aggiungi|补充|أضف المزيد|और जोड़ें
Ещё {count}|{count} more|{count} weitere|{count} más|Encore {count}|Altri {count}|还有 {count} 项|{count} إضافية|{count} और
Зачем вы обычно читаете статьи?|What do you read articles for?|Wofür liest du Artikel?|¿Para qué lees artículos?|Pourquoi lisez-vous des articles ?|Perché leggi articoli?|你通常为什么阅读文章？|لماذا تقرأ المقالات عادةً؟|आप लेख किसलिए पढ़ते हैं?
Например: выбираю инструменты для работы, учусь оценивать AI или читаю об истории для удовольствия.|For example: choosing tools for work, learning to evaluate AI, or enjoying history.|Zum Beispiel: Arbeitswerkzeuge auswählen, KI-Bewertung lernen oder Geschichte zum Vergnügen lesen.|Por ejemplo: elegir herramientas, aprender a evaluar IA o disfrutar de la historia.|Par exemple : choisir des outils, apprendre à évaluer l’IA ou lire de l’histoire par plaisir.|Per esempio: scegliere strumenti, imparare a valutare l’AI o leggere storia per piacere.|例如：挑选工作工具、学习评估 AI，或出于爱好阅读历史。|مثل اختيار أدوات للعمل، أو تعلم تقييم الذكاء الاصطناعي، أو الاستمتاع بالتاريخ.|जैसे काम के औज़ार चुनना, AI का मूल्यांकन सीखना या इतिहास पढ़ने का आनंद लेना।
Какие темы вы выбираете сами?|Which topics do you choose to read about?|Welche Themen wählst du selbst?|¿Qué temas eliges leer?|Quels sujets choisissez-vous de lire ?|Quali argomenti scegli di leggere?|你会主动阅读哪些主题？|ما المواضيع التي تختار قراءتها؟|आप खुद किन विषयों को पढ़ना चुनते हैं?
Укажите конкретные темы, каждую с новой строки. Например: оценка AI, история городов, домашняя выпечка.|Add specific topics, one per line. For example: AI evaluation, city history, home baking.|Konkrete Themen, eines pro Zeile. Zum Beispiel: KI-Bewertung, Stadtgeschichte, Brotbacken.|Temas concretos, uno por línea. Por ejemplo: evaluación de IA, historia urbana, repostería.|Des sujets précis, un par ligne. Par exemple : évaluation de l’IA, histoire des villes, pâtisserie.|Argomenti specifici, uno per riga. Per esempio: valutazione AI, storia delle città, cucina.|填写具体主题，每行一个。例如：AI 评估、城市历史、家庭烘焙。|أضف مواضيع محددة، كل منها بسطر. مثل تقييم الذكاء الاصطناعي وتاريخ المدن والخبز.|ठोस विषय अलग-अलग पंक्तियों में लिखें। जैसे AI मूल्यांकन, शहरों का इतिहास, घर में बेकिंग।
Что вам уже не нужно объяснять с нуля?|What don’t you need explained from scratch?|Was muss man dir nicht von Grund auf erklären?|¿Qué no necesitas que te expliquen desde cero?|Que n’avez-vous pas besoin de découvrir de zéro ?|Cosa non serve spiegarti da zero?|哪些内容不需要从头向你解释？|ما الذي لا تحتاج إلى شرحه من البداية؟|कौन-सी बातें आपको शुरू से समझाने की ज़रूरत नहीं है?
Назовите знакомую тему и приведите пример того, что вы уже умеете или понимаете.|Name a familiar topic and give an example of what you can do or understand.|Nenne ein vertrautes Thema und ein Beispiel für dein Wissen oder Können.|Nombra un tema conocido y un ejemplo de lo que sabes hacer o entiendes.|Nommez un sujet familier et donnez un exemple de ce que vous savez faire ou comprenez.|Indica un argomento familiare e un esempio di ciò che sai fare o capisci.|填写熟悉的主题，并举例说明你已掌握的技能或知识。|اذكر موضوعًا تعرفه ومثالًا لما تستطيع فعله أو فهمه.|कोई परिचित विषय और उसमें अपने ज्ञान या कौशल का उदाहरण दें।
Я только начинаю в этих темах|I’m just starting with these topics|Ich fange bei diesen Themen erst an|Estoy empezando con estos temas|Je débute dans ces sujets|Sto iniziando con questi argomenti|这些主题我刚开始学习|أنا مبتدئ في هذه المواضيع|मैं इन विषयों में अभी शुरुआत कर रहा हूँ
Продолжить|Continue|Weiter|Continuar|Continuer|Continua|继续|متابعة|जारी रखें
Напишите свой ответ.|Please add your answer.|Schreib bitte deine Antwort.|Escribe tu respuesta.|Écrivez votre réponse.|Scrivi la tua risposta.|请填写回答。|اكتب إجابتك.|अपना जवाब लिखें।
Профиль сохранён. Попробуем на статье?|Profile saved. Try it on an article?|Profil gespeichert. An einem Artikel ausprobieren?|Perfil guardado. ¿Lo probamos en un artículo?|Profil enregistré. Essayons sur un article ?|Profilo salvato. Proviamo su un articolo?|资料已保存。试着阅读一篇文章吧？|حُفظ الملف. لنجربه على مقال؟|प्रोफ़ाइल सहेजी गई। किसी लेख पर आज़माएँ?
Наведите курсор на заголовок статьи. Attention подскажет, стоит ли читать, и предложит фрагменты, если найдёт подходящие.|Hover over an article’s title. Attention will suggest whether to read it and offer passages when it finds suitable ones.|Fahre über den Artikeltitel. Attention gibt einen Lesetipp und zeigt passende Textstellen, falls es welche findet.|Pasa el cursor sobre el título. Attention te aconsejará si leer y mostrará pasajes cuando encuentre adecuados.|Survolez le titre. Attention vous conseillera la lecture et proposera des passages s’il en trouve de pertinents.|Passa sul titolo. Attention suggerirà se leggere e proporrà passaggi quando ne trova di adatti.|将光标移到文章标题上。Attention 会给出阅读建议，并在找到合适片段时显示它们。|مرر المؤشر على عنوان المقال. سيقترح Attention ما إذا كانت قراءته مفيدة، ويعرض مقاطع مناسبة إن وجدها.|लेख के शीर्षक पर कर्सर ले जाएँ। Attention पढ़ने का सुझाव देगा और उपयुक्त अंश मिलने पर दिखाएगा।
Вернуться к статье|Return to the article|Zurück zum Artikel|Volver al artículo|Revenir à l’article|Torna all’articolo|返回文章|العودة إلى المقال|लेख पर वापस जाएँ
Добавить профиль из другого AI|Add a profile from the other AI|Profil aus der anderen KI ergänzen|Añadir perfil de otra IA|Ajouter le profil de l’autre IA|Aggiungi il profilo dell’altra AI|添加另一个 AI 的资料|أضف ملفًا من الذكاء الاصطناعي الآخر|दूसरे AI की प्रोफ़ाइल जोड़ें
Эта вкладка уже закрыта. Откройте любую статью и наведите курсор на заголовок.|That tab is closed. Open an article and hover over its title.|Dieser Tab ist geschlossen. Öffne einen Artikel und fahre über den Titel.|La pestaña está cerrada. Abre un artículo y pasa el cursor por el título.|Cet onglet est fermé. Ouvrez un article et survolez son titre.|La scheda è chiusa. Apri un articolo e passa sul titolo.|该标签页已关闭。打开任意文章，将光标移到标题上。|أُغلقت علامة التبويب. افتح مقالًا ومرر المؤشر على عنوانه.|वह टैब बंद है। कोई लेख खोलकर शीर्षक पर कर्सर ले जाएँ।
Ответ не удалось прочитать. Скопируйте весь ответ на наш запрос, включая начало и конец.|We couldn’t read that answer. Copy the full answer to our prompt, including the beginning and end.|Die Antwort war nicht lesbar. Kopiere die gesamte Antwort auf unsere Anfrage, einschließlich Anfang und Ende.|No pudimos leer la respuesta. Copia la respuesta completa a nuestra petición, incluidos principio y final.|La réponse n’a pas pu être lue. Copiez la réponse entière à notre demande, du début à la fin.|Non riusciamo a leggere la risposta. Copia tutta la risposta alla nostra richiesta, dall’inizio alla fine.|无法读取该回答。请复制对我们请求的完整回答，包括开头和结尾。|تعذرت قراءة الإجابة. انسخ الإجابة كاملة عن طلبنا، من البداية إلى النهاية.|जवाब पढ़ा नहीं जा सका। हमारे अनुरोध का पूरा जवाब शुरू से अंत तक कॉपी करें।
Защитим ваш профиль|Protect your profile|Schütze dein Profil|Protege tu perfil|Protégeons votre profil|Proteggi il tuo profilo|保护你的资料|لنحمِ ملفك|अपनी प्रोफ़ाइल सुरक्षित करें
Профиль будет храниться в этом браузере в зашифрованном виде. Придумайте пароль, чтобы открывать его после перезапуска браузера.|Your profile will be encrypted in this browser. Choose a password to unlock it after restarting the browser.|Dein Profil wird in diesem Browser verschlüsselt. Wähle ein Passwort zum Entsperren nach einem Browser-Neustart.|Tu perfil se cifrará en este navegador. Elige una contraseña para abrirlo tras reiniciar.|Votre profil sera chiffré dans ce navigateur. Choisissez un mot de passe pour le retrouver après un redémarrage.|Il profilo sarà cifrato in questo browser. Scegli una password per aprirlo dopo il riavvio.|资料会加密保存在此浏览器中。设置密码，以便重启浏览器后解锁。|سيُشفّر ملفك في هذا المتصفح. اختر كلمة مرور لفتحه بعد إعادة تشغيل المتصفح.|प्रोफ़ाइल इस ब्राउज़र में एन्क्रिप्ट होकर रहेगी। ब्राउज़र दोबारा खोलने के बाद अनलॉक करने के लिए पासवर्ड चुनें।
Профиль помогает учитывать ваши интересы и опыт, но не гарантирует точность каждой рекомендации.|Your profile helps account for your interests and experience, but doesn’t guarantee every recommendation is right.|Dein Profil berücksichtigt Interessen und Erfahrung, garantiert aber keine fehlerfreien Empfehlungen.|Tu perfil ayuda a considerar intereses y experiencia, pero no garantiza que cada consejo sea acertado.|Votre profil aide à tenir compte de vos intérêts et expérience, sans garantir chaque conseil.|Il profilo aiuta a considerare interessi ed esperienza, ma non garantisce ogni consiglio.|资料帮助考虑你的兴趣和经验，但不能保证每条建议都准确。|يساعد الملف على مراعاة اهتماماتك وخبرتك، لكنه لا يضمن صحة كل اقتراح.|प्रोफ़ाइल रुचियों और अनुभव को ध्यान में रखती है, पर हर सुझाव की सटीकता की गारंटी नहीं देती।
Запрос для AI|Prompt for the AI|Anfrage an die KI|Petición para la IA|Demande pour l’IA|Richiesta per l’AI|给 AI 的请求|طلب للذكاء الاصطناعي|AI के लिए अनुरोध
Назад|Back|Zurück|Atrás|Retour|Indietro|返回|رجوع|वापस
Сохранить и попробовать|Save and try it|Speichern und ausprobieren|Guardar y probar|Enregistrer et essayer|Salva e prova|保存并试用|احفظ وجرب|सहेजें और आज़माएँ
Изучаю: {topic}|Learning: {topic}|Ich lerne: {topic}|Aprendiendo: {topic}|J’apprends : {topic}|Sto imparando: {topic}|正在学习：{topic}|أتعلم: {topic}|सीख रहा हूँ: {topic}
Для отдыха: {topic}|For enjoyment: {topic}|Zur Unterhaltung: {topic}|Por placer: {topic}|Pour le plaisir : {topic}|Per piacere: {topic}|休闲：{topic}|للمتعة: {topic}|मनोरंजन के लिए: {topic}
Сначала профиль, затем советы именно для вас.|First your profile, then recommendations for you.|Erst dein Profil, dann Empfehlungen für dich.|Primero tu perfil, luego recomendaciones para ti.|D’abord votre profil, puis des conseils pour vous.|Prima il profilo, poi consigli per te.|先建立资料，再获得适合你的建议。|ملفك أولًا، ثم اقتراحات تناسبك.|पहले प्रोफ़ाइल, फिर आपके लिए सुझाव।
`;
