// Same column order as profile.ts. Only interface copy, never personal values.
export const ONBOARDING_ROWS = `
Твой ИИ тебя знает.|Your AI knows you.|Deine KI kennt dich.|Tu IA te conoce.|Votre IA vous connaît.|La tua AI ti conosce.|你的 AI 了解你。|مساعدك الذكي يعرفك.|आपका AI आपको जानता है।
Теперь используй эти знания на своих условиях.|Now use that knowledge on your terms.|Nutze dieses Wissen jetzt nach deinen eigenen Regeln.|Ahora usa ese conocimiento a tu manera.|Utilisez maintenant ce savoir selon vos propres règles.|Ora usa queste conoscenze alle tue condizioni.|现在，按你的意愿使用这些了解。|استخدم الآن هذه المعرفة وفق شروطك.|अब इस जानकारी का इस्तेमाल अपनी शर्तों पर करें।
Перенеси свой профиль в Attention — и|Bring your profile into Attention — and|Übertrage dein Profil nach Attention — und|Lleva tu perfil a Attention y|Transférez votre profil dans Attention et|Porta il tuo profilo in Attention e|将你的个人资料带入 Attention，|انقل ملفك الشخصي إلى Attention، ثم|अपनी प्रोफ़ाइल Attention में लाएँ — और
сам выбирай, что читать.|choose for yourself what to read.|entscheide selbst, was du liest.|decide tú qué leer.|choisissez vous-même quoi lire.|scegli tu cosa leggere.|自己决定读什么。|اختر بنفسك ما تقرأه.|खुद चुनें कि क्या पढ़ना है।
По своим интересам, а не по указке чужих алгоритмов.|Based on your interests, not someone else’s algorithms.|Nach deinen Interessen, nicht nach fremden Algorithmen.|Según tus intereses, no los algoritmos de otros.|Selon vos intérêts, pas les algorithmes des autres.|In base ai tuoi interessi, non agli algoritmi altrui.|依据你的兴趣，而不是听从别人的算法。|بناءً على اهتماماتك، لا ما تمليه خوارزميات الآخرين.|अपनी रुचियों के अनुसार, दूसरों के एल्गोरिदम के इशारों पर नहीं।
Забрать свой профиль →|Take my profile with me →|Mein Profil mitnehmen →|Llevarme mi perfil →|Emporter mon profil →|Porta con te il tuo profilo →|带走我的个人资料 →|خذ ملفك الشخصي معك ←|अपनी प्रोफ़ाइल साथ ले जाएँ →
Что стоит вашего времени?|What deserves your time?|Was ist deine Zeit wert?|¿Qué merece tu tiempo?|Qu’est-ce qui mérite votre temps ?|Cosa merita il tuo tempo?|什么值得你花时间？|ما الذي يستحق وقتك؟|आपके समय के लायक क्या है?
Attention помогает выбрать, что читать и на каких фрагментах остановиться.|Attention helps you choose what to read and which passages to focus on.|Attention hilft dir, Lesestoff und wichtige Textstellen auszuwählen.|Attention te ayuda a elegir qué leer y en qué pasajes detenerte.|Attention vous aide à choisir quoi lire et quels passages approfondir.|Attention ti aiuta a scegliere cosa leggere e su quali passaggi soffermarti.|Attention 帮你选择值得阅读的文章和片段。|يساعدك Attention على اختيار ما تقرأ والمقاطع التي تستحق التركيز.|Attention पढ़ने की सामग्री और ध्यान देने वाले अंश चुनने में मदद करता है।
Одна статья. Разный смысл для вас.|One article. Different value for you.|Ein Artikel. Unterschiedlicher Nutzen.|Un artículo. Distinto valor para ti.|Un article. Une utilité différente pour vous.|Un articolo. Un valore diverso per te.|同一篇文章，对你有不同价值。|مقال واحد، وقيمة مختلفة لك.|एक लेख। आपके लिए अलग उपयोगिता।
Учебный пример|Illustrative example|Anschauliches Beispiel|Ejemplo ilustrativo|Exemple illustratif|Esempio illustrativo|演示示例|مثال توضيحي|समझाने के लिए उदाहरण
Как оценивать ответы AI: первые шаги|Evaluating AI answers: getting started|KI-Antworten bewerten: erste Schritte|Evaluar respuestas de IA: primeros pasos|Évaluer les réponses de l’IA : premiers pas|Valutare le risposte AI: primi passi|如何评估 AI 回答：入门|تقييم إجابات الذكاء الاصطناعي: البداية|AI के जवाब परखना: शुरुआत
Я изучаю эту тему|I’m learning this topic|Ich lerne dieses Thema|Estoy aprendiendo este tema|Je découvre ce sujet|Sto imparando questo argomento|我正在学习这个主题|أتعلم هذا الموضوع|मैं यह विषय सीख रहा हूँ
Я уже знаю основы|I already know the basics|Ich kenne die Grundlagen|Ya conozco lo básico|Je connais déjà les bases|Conosco già le basi|我已了解基础知识|أعرف الأساسيات بالفعل|मुझे बुनियादी बातें आती हैं
Стоит прочитать|Worth reading|Lesenswert|Vale la pena leer|À lire|Vale la pena leggere|值得阅读|يستحق القراءة|पढ़ना उपयोगी होगा
Критерии и примеры помогут начать оценивать ответы моделей.|Criteria and examples will help you start evaluating model answers.|Kriterien und Beispiele helfen dir beim Einstieg in die Bewertung von Modellantworten.|Los criterios y ejemplos te ayudarán a empezar a evaluar respuestas.|Les critères et exemples vous aideront à commencer à évaluer les réponses.|Criteri ed esempi ti aiuteranno a iniziare a valutare le risposte.|标准和示例能帮助你开始评估模型回答。|تساعدك المعايير والأمثلة على بدء تقييم إجابات النماذج.|मानदंड और उदाहरण मॉडल के जवाब परखना शुरू करने में मदद करेंगे।
Основы можно пропустить|You can skip the basics|Die Grundlagen kannst du überspringen|Puedes saltarte lo básico|Vous pouvez passer les bases|Puoi saltare le basi|可以跳过基础内容|يمكنك تجاوز الأساسيات|बुनियादी बातें छोड़ सकते हैं
Начните с примера сложной ошибки — вводная часть вам уже знакома.|Start with the tricky error example — you already know the introduction.|Beginne mit dem Beispiel eines kniffligen Fehlers – die Einführung kennst du bereits.|Empieza por el ejemplo del error difícil: ya conoces la introducción.|Commencez par l’exemple d’erreur complexe : vous connaissez déjà l’introduction.|Inizia dall’esempio di errore difficile: conosci già l’introduzione.|从复杂错误的示例开始——入门部分你已熟悉。|ابدأ بمثال الخطأ المعقد، فالمقدمة مألوفة لك.|जटिल गलती के उदाहरण से शुरू करें — परिचय आप पहले से जानते हैं।
Чтобы советовать именно вам, Attention нужно немного вас узнать.|To make recommendations for you, Attention needs to get to know you.|Für persönliche Empfehlungen muss Attention dich etwas kennenlernen.|Para recomendarte lecturas, Attention necesita conocerte un poco.|Pour vous conseiller, Attention a besoin de vous connaître un peu.|Per consigliarti, Attention deve conoscerti un po’.|为了给你合适的建议，Attention 需要先了解你。|ليقدم Attention اقتراحات تناسبك، يحتاج إلى معرفتك قليلًا.|आपके लिए सुझाव देने के लिए Attention को आपको थोड़ा जानना होगा।
Настроить под меня|Make it personal|Auf mich abstimmen|Adaptarlo a mí|Personnaliser|Personalizza per me|为我设置|خصصه لي|मेरे लिए सेट करें
Кто уже знает ваши интересы?|Who already knows your interests?|Wer kennt deine Interessen schon?|¿Quién conoce ya tus intereses?|Qui connaît déjà vos intérêts ?|Chi conosce già i tuoi interessi?|谁已经了解你的兴趣？|من يعرف اهتماماتك بالفعل؟|आपकी रुचियों को कौन पहले से जानता है?
Выберите AI, с которым обсуждали работу, учёбу или увлечения. Он поможет собрать профиль из знакомого ему контекста. Второй можно добавить позже.|Choose the AI you’ve talked to about work, learning or hobbies. It can help build a profile from the context it knows. You can add another profile later.|Wähle die KI, mit der du über Arbeit, Lernen oder Hobbys gesprochen hast. Sie hilft mit dem Kontext, den sie kennt. Weitere Profile kannst du später ergänzen.|Elige la IA con la que hablas de trabajo, aprendizaje o aficiones. Te ayudará con el contexto que conoce. Puedes añadir otro perfil después.|Choisissez l’IA avec laquelle vous avez parlé de travail, d’études ou de loisirs. Elle utilisera le contexte qu’elle connaît. Vous pourrez ajouter un autre profil ensuite.|Scegli l’AI con cui hai parlato di lavoro, studio o hobby. Ti aiuterà con il contesto che conosce. Potrai aggiungere un altro profilo dopo.|选择聊过工作、学习或爱好的 AI。它能根据已有背景帮助整理资料，以后还可以添加另一个。|اختر الذكاء الاصطناعي الذي تحدثت معه عن العمل أو التعلم أو الهوايات. سيساعدك بالسياق الذي يعرفه، ويمكنك إضافة الآخر لاحقًا.|वह AI चुनें जिससे काम, पढ़ाई या शौक पर बात की है। वह परिचित संदर्भ से प्रोफ़ाइल बनाने में मदद करेगा। दूसरा बाद में जोड़ सकते हैं।
Я пока не пользуюсь ими|I don’t use these yet|Ich nutze diese Dienste noch nicht|Aún no uso estos servicios|Je n’utilise aucun de ces services|Non uso ancora questi servizi|我还没用过这些服务|لا أستخدم هذه الخدمات بعد|मैं अभी इन सेवाओं का उपयोग नहीं करता
Ответьте на несколько вопросов о своих задачах и опыте. Чем конкретнее примеры, тем полезнее рекомендации.|Answer a few questions about your goals and experience. Specific examples make recommendations more useful.|Beantworte einige Fragen zu Zielen und Erfahrung. Konkrete Beispiele machen Empfehlungen hilfreicher.|Responde unas preguntas sobre tus objetivos y experiencia. Los ejemplos concretos ayudan a recomendar mejor.|Répondez à quelques questions sur vos objectifs et votre expérience. Des exemples précis rendent les conseils plus utiles.|Rispondi a qualche domanda su obiettivi ed esperienza. Esempi concreti rendono i consigli più utili.|回答几个关于目标和经验的问题。示例越具体，建议越有用。|أجب عن أسئلة حول أهدافك وخبرتك. الأمثلة المحددة تجعل الاقتراحات أنفع.|लक्ष्यों और अनुभव के बारे में कुछ सवालों के जवाब दें। ठोस उदाहरण सुझावों को अधिक उपयोगी बनाते हैं।
Ответить на вопросы|Answer a few questions|Fragen beantworten|Responder preguntas|Répondre aux questions|Rispondi alle domande|回答问题|أجب عن الأسئلة|सवालों के जवाब दें
Скопируйте весь ответ и вставьте сюда.|Copy the whole answer and paste it here.|Kopiere die ganze Antwort hierher.|Copia toda la respuesta y pégala aquí.|Copiez toute la réponse et collez-la ici.|Copia tutta la risposta e incollala qui.|复制完整回答并粘贴到这里。|انسخ الإجابة كاملة والصقها هنا.|पूरा जवाब कॉपी करके यहाँ पेस्ट करें।
Ответ от AI|The AI’s answer|Antwort der KI|Respuesta de la IA|Réponse de l’IA|Risposta dell’AI|AI 的回答|إجابة الذكاء الاصطناعي|AI का जवाब
Вставьте ответ целиком — разберём его за вас.|Paste the whole answer — we’ll sort it out for you.|Füge die gesamte Antwort ein – wir bereiten sie auf.|Pega toda la respuesta: nosotros la organizamos.|Collez toute la réponse : nous la mettrons en forme.|Incolla tutta la risposta: la organizziamo noi.|粘贴完整回答，我们来整理。|الصق الإجابة كاملة وسنرتبها لك.|पूरा जवाब पेस्ट करें — हम उसे व्यवस्थित करेंगे।
Посмотреть мой профиль|Preview my profile|Mein Profil ansehen|Ver mi perfil|Voir mon profil|Vedi il mio profilo|查看我的资料|اعرض ملفي|मेरी प्रोफ़ाइल देखें
Всё верно?|Does this look right?|Stimmt das so?|¿Está todo bien?|Tout est correct ?|È tutto corretto?|这些信息准确吗？|هل هذا صحيح؟|क्या यह सही है?
Исправьте неточности или удалите лишнее. Эти сведения помогут выбирать чтение для вас.|Correct anything inaccurate or remove what doesn’t belong. This will guide your reading recommendations.|Korrigiere Ungenaues oder entferne Unpassendes. Diese Angaben helfen bei deinen Leseempfehlungen.|Corrige lo inexacto o elimina lo que sobra. Estos datos orientarán tus recomendaciones.|Corrigez les erreurs ou retirez le superflu. Ces informations guideront vos conseils de lecture.|Correggi le inesattezze o elimina ciò che non serve. Queste informazioni guideranno i consigli.|修正不准确的信息或删除多余内容，这些信息将用于推荐阅读。|صحح الأخطاء أو احذف ما لا يناسبك. ستوجه هذه المعلومات اقتراحات القراءة.|गलत बातें सुधारें या अनावश्यक जानकारी हटाएँ। यही पढ़ने के सुझावों का आधार बनेगी।
Сейчас мне важно|What matters to me now|Was mir gerade wichtig ist|Lo que me importa ahora|Ce qui compte pour moi maintenant|Cosa mi importa adesso|我目前关注的目标|ما يهمني الآن|अभी मेरे लिए ज़रूरी है
Мне интересно|I’m interested in|Mich interessiert|Me interesa|Ce qui m’intéresse|Mi interessa|我感兴趣的主题|ما يثير اهتمامي|मेरी रुचियाँ
Что я знаю и изучаю|What I know and am learning|Was ich weiß und lerne|Lo que sé y estoy aprendiendo|Ce que je sais et apprends|Cosa so e sto imparando|我知道什么、正在学习什么|ما أعرفه وما أتعلمه|मैं क्या जानता और सीख रहा हूँ
Все подробности профиля|All profile details|Alle Profildetails|Todos los detalles|Tous les détails du profil|Tutti i dettagli del profilo|全部资料详情|كل تفاصيل الملف|प्रोफ़ाइल की सभी जानकारी
Дополнить|Add more|Ergänzen|Añadir|Compléter|Aggiungi|补充|أضف المزيد|और जोड़ें
Ещё {count}|{count} more|{count} weitere|{count} más|Encore {count}|Altri {count}|还有 {count} 项|{count} إضافية|{count} और
Зачем вы обычно читаете статьи?|What do you read articles for?|Wofür liest du Artikel?|¿Para qué lees artículos?|Pourquoi lisez-vous des articles ?|Perché leggi articoli?|你通常为什么阅读文章？|لماذا تقرأ المقالات عادةً؟|आप लेख किसलिए पढ़ते हैं?
Например: выбираю инструменты для работы, учусь оценивать AI или читаю об истории для удовольствия.|For example: choosing tools for work, learning to evaluate AI, or enjoying history.|Zum Beispiel: Arbeitswerkzeuge auswählen, KI-Bewertung lernen oder Geschichte zum Vergnügen lesen.|Por ejemplo: elegir herramientas, aprender a evaluar IA o disfrutar de la historia.|Par exemple : choisir des outils, apprendre à évaluer l’IA ou lire de l’histoire par plaisir.|Per esempio: scegliere strumenti, imparare a valutare l’AI o leggere storia per piacere.|例如：挑选工作工具、学习评估 AI，或出于爱好阅读历史。|مثل اختيار أدوات للعمل، أو تعلم تقييم الذكاء الاصطناعي، أو الاستمتاع بالتاريخ.|जैसे काम के औज़ार चुनना, AI का मूल्यांकन सीखना या इतिहास पढ़ने का आनंद लेना।
Какие темы вы выбираете сами?|Which topics do you choose to read about?|Welche Themen wählst du selbst?|¿Qué temas eliges leer?|Quels sujets choisissez-vous de lire ?|Quali argomenti scegli di leggere?|你会主动阅读哪些主题？|ما المواضيع التي تختار قراءتها؟|आप खुद किन विषयों को पढ़ना चुनते हैं?
Укажите конкретные темы, каждую с новой строки. Например: оценка AI, история городов, домашняя выпечка.|Add specific topics, one per line. For example: AI evaluation, city history, home baking.|Konkrete Themen, eines pro Zeile. Zum Beispiel: KI-Bewertung, Stadtgeschichte, Brotbacken.|Temas concretos, uno por línea. Por ejemplo: evaluación de IA, historia urbana, repostería.|Des sujets précis, un par ligne. Par exemple : évaluation de l’IA, histoire des villes, pâtisserie.|Argomenti specifici, uno per riga. Per esempio: valutazione AI, storia delle città, cucina.|填写具体主题，每行一个。例如：AI 评估、城市历史、家庭烘焙。|أضف مواضيع محددة، كل منها بسطر. مثل تقييم الذكاء الاصطناعي وتاريخ المدن والخبز.|ठोस विषय अलग-अलग पंक्तियों में लिखें। जैसे AI मूल्यांकन, शहरों का इतिहास, घर में बेकिंग।
Что вам уже не нужно объяснять с нуля?|What don’t you need explained from scratch?|Was muss man dir nicht von Grund auf erklären?|¿Qué no necesitas que te expliquen desde cero?|Que n’avez-vous pas besoin de découvrir de zéro ?|Cosa non serve spiegarti da zero?|哪些内容不需要从头向你解释？|ما الذي لا تحتاج إلى شرحه من البداية؟|कौन-सी बातें आपको शुरू से समझाने की ज़रूरत नहीं है?
Назовите знакомую тему и приведите пример того, что вы уже умеете или понимаете.|Name a familiar topic and give an example of what you can do or understand.|Nenne ein vertrautes Thema und ein Beispiel für dein Wissen oder Können.|Nombra un tema conocido y un ejemplo de lo que sabes hacer o entiendes.|Nommez un sujet familier et donnez un exemple de ce que vous savez faire ou comprenez.|Indica un argomento familiare e un esempio di ciò che sai fare o capisci.|填写熟悉的主题，并举例说明你已掌握的技能或知识。|اذكر موضوعًا تعرفه ومثالًا لما تستطيع فعله أو فهمه.|कोई परिचित विषय और उसमें अपने ज्ञान या कौशल का उदाहरण दें।
Я только начинаю в этих темах|I’m just starting with these topics|Ich fange bei diesen Themen erst an|Estoy empezando con estos temas|Je débute dans ces sujets|Sto iniziando con questi argomenti|这些主题我刚开始学习|أنا مبتدئ في هذه المواضيع|मैं इन विषयों में अभी शुरुआत कर रहा हूँ
Продолжить|Continue|Weiter|Continuar|Continuer|Continua|继续|متابعة|जारी रखें
Напишите свой ответ.|Please add your answer.|Schreib bitte deine Antwort.|Escribe tu respuesta.|Écrivez votre réponse.|Scrivi la tua risposta.|请填写回答。|اكتب إجابتك.|अपना जवाब लिखें।
Профиль сохранён. Попробуем на статье?|Profile saved. Try it on an article?|Profil gespeichert. An einem Artikel ausprobieren?|Perfil guardado. ¿Lo probamos en un artículo?|Profil enregistré. Essayons sur un article ?|Profilo salvato. Proviamo su un articolo?|资料已保存。试着阅读一篇文章吧？|حُفظ الملف. لنجربه على مقال؟|प्रोफ़ाइल सहेजी गई। किसी लेख पर आज़माएँ?
Наведите курсор на заголовок статьи. Attention подскажет, стоит ли читать, и предложит фрагменты, если найдёт подходящие.|Hover over an article’s title. Attention will suggest whether to read it and offer passages when it finds suitable ones.|Fahre über den Artikeltitel. Attention gibt einen Lesetipp und zeigt passende Textstellen, falls es welche findet.|Pasa el cursor sobre el título. Attention te aconsejará si leer y mostrará pasajes cuando encuentre adecuados.|Survolez le titre. Attention vous conseillera la lecture et proposera des passages s’il en trouve de pertinents.|Passa sul titolo. Attention suggerirà se leggere e proporrà passaggi quando ne trova di adatti.|将光标移到文章标题上。Attention 会给出阅读建议，并在找到合适片段时显示它们。|مرر المؤشر على عنوان المقال. سيقترح Attention ما إذا كانت قراءته مفيدة، ويعرض مقاطع مناسبة إن وجدها.|लेख के शीर्षक पर कर्सर ले जाएँ। Attention पढ़ने का सुझाव देगा और उपयुक्त अंश मिलने पर दिखाएगा।
Вернуться к статье|Return to the article|Zurück zum Artikel|Volver al artículo|Revenir à l’article|Torna all’articolo|返回文章|العودة إلى المقال|लेख पर वापस जाएँ
Добавить профиль из другого AI|Add a profile from the other AI|Profil aus der anderen KI ergänzen|Añadir perfil de otra IA|Ajouter le profil de l’autre IA|Aggiungi il profilo dell’altra AI|添加另一个 AI 的资料|أضف ملفًا من الذكاء الاصطناعي الآخر|दूसरे AI की प्रोफ़ाइल जोड़ें
Эта вкладка уже закрыта. Откройте любую статью и наведите курсор на заголовок.|That tab is closed. Open an article and hover over its title.|Dieser Tab ist geschlossen. Öffne einen Artikel und fahre über den Titel.|La pestaña está cerrada. Abre un artículo y pasa el cursor por el título.|Cet onglet est fermé. Ouvrez un article et survolez son titre.|La scheda è chiusa. Apri un articolo e passa sul titolo.|该标签页已关闭。打开任意文章，将光标移到标题上。|أُغلقت علامة التبويب. افتح مقالًا ومرر المؤشر على عنوانه.|वह टैब बंद है। कोई लेख खोलकर शीर्षक पर कर्सर ले जाएँ।
Ответ не удалось прочитать. Скопируйте весь ответ на наш запрос, включая начало и конец.|We couldn’t read that answer. Copy the full answer to our prompt, including the beginning and end.|Die Antwort war nicht lesbar. Kopiere die gesamte Antwort auf unsere Anfrage, einschließlich Anfang und Ende.|No pudimos leer la respuesta. Copia la respuesta completa a nuestra petición, incluidos principio y final.|La réponse n’a pas pu être lue. Copiez la réponse entière à notre demande, du début à la fin.|Non riusciamo a leggere la risposta. Copia tutta la risposta alla nostra richiesta, dall’inizio alla fine.|无法读取该回答。请复制对我们请求的完整回答，包括开头和结尾。|تعذرت قراءة الإجابة. انسخ الإجابة كاملة عن طلبنا، من البداية إلى النهاية.|जवाब पढ़ा नहीं जा सका। हमारे अनुरोध का पूरा जवाब शुरू से अंत तक कॉपी करें।
А теперь защитим твои данные|Now let’s protect your data|Jetzt schützen wir deine Daten|Ahora protejamos tus datos|Protégeons maintenant vos données|Ora proteggiamo i tuoi dati|现在，保护你的数据|والآن لنحمِ بياناتك|अब आपके डेटा को सुरक्षित करते हैं
Придумай пароль. Attention зашифрует твой профиль и другие данные в этом браузере.|Choose a password. Attention will encrypt your profile and other data in this browser.|Wähle ein Passwort. Attention verschlüsselt dein Profil und weitere Daten in diesem Browser.|Elige una contraseña. Attention cifrará tu perfil y otros datos en este navegador.|Choisissez un mot de passe. Attention chiffrera votre profil et vos autres données dans ce navigateur.|Scegli una password. Attention cifrerà il tuo profilo e gli altri dati in questo browser.|设置一个密码。Attention 会在此浏览器中加密你的个人资料和其他数据。|اختر كلمة مرور. سيشفّر Attention ملفك الشخصي وبياناتك الأخرى في هذا المتصفح.|एक पासवर्ड चुनें। Attention आपकी प्रोफ़ाइल और अन्य डेटा को इस ब्राउज़र में एन्क्रिप्ट करेगा।
Профиль помогает учитывать ваши интересы и опыт, но не гарантирует точность каждой рекомендации.|Your profile helps account for your interests and experience, but doesn’t guarantee every recommendation is right.|Dein Profil berücksichtigt Interessen und Erfahrung, garantiert aber keine fehlerfreien Empfehlungen.|Tu perfil ayuda a considerar intereses y experiencia, pero no garantiza que cada consejo sea acertado.|Votre profil aide à tenir compte de vos intérêts et expérience, sans garantir chaque conseil.|Il profilo aiuta a considerare interessi ed esperienza, ma non garantisce ogni consiglio.|资料帮助考虑你的兴趣和经验，但不能保证每条建议都准确。|يساعد الملف على مراعاة اهتماماتك وخبرتك، لكنه لا يضمن صحة كل اقتراح.|प्रोफ़ाइल रुचियों और अनुभव को ध्यान में रखती है, पर हर सुझाव की सटीकता की गारंटी नहीं देती।
Запрос для AI|Prompt for the AI|Anfrage an die KI|Petición para la IA|Demande pour l’IA|Richiesta per l’AI|给 AI 的请求|طلب للذكاء الاصطناعي|AI के लिए अनुरोध
Назад|Back|Zurück|Atrás|Retour|Indietro|返回|رجوع|वापस
Сохранить и попробовать|Save and try it|Speichern und ausprobieren|Guardar y probar|Enregistrer et essayer|Salva e prova|保存并试用|احفظ وجرب|सहेजें और आज़माएँ
Изучаю: {topic}|Learning: {topic}|Ich lerne: {topic}|Aprendiendo: {topic}|J’apprends : {topic}|Sto imparando: {topic}|正在学习：{topic}|أتعلم: {topic}|सीख रहा हूँ: {topic}
Для отдыха: {topic}|For enjoyment: {topic}|Zur Unterhaltung: {topic}|Por placer: {topic}|Pour le plaisir : {topic}|Per piacere: {topic}|休闲：{topic}|للمتعة: {topic}|मनोरंजन के लिए: {topic}
Сначала профиль, затем советы именно для вас.|First your profile, then recommendations for you.|Erst dein Profil, dann Empfehlungen für dich.|Primero tu perfil, luego recomendaciones para ti.|D’abord votre profil, puis des conseils pour vous.|Prima il profilo, poi consigli per te.|先建立资料，再获得适合你的建议。|ملفك أولًا، ثم اقتراحات تناسبك.|पहले प्रोफ़ाइल, फिर आपके लिए सुझाव।
По желанию|Optional|Optional|Opcional|Facultatif|Facoltativo|可选|اختياري|वैकल्पिक
Профиль готов — уже можно начинать|Your profile is ready. You can start now.|Dein Profil ist bereit. Du kannst loslegen.|Tu perfil está listo. Ya puedes empezar.|Votre profil est prêt. Vous pouvez commencer.|Il profilo è pronto. Puoi iniziare.|资料已准备好，可以开始了|ملفك جاهز. يمكنك البدء الآن.|प्रोफ़ाइल तैयार है। अब शुरू कर सकते हैं।
Хотите помочь Attention лучше понимать, что вам уже знакомо? Добавьте один из источников ниже.|Want to help Attention recognise what you already know? Add one of the sources below.|Möchtest du Attention helfen, vertraute Inhalte besser zu erkennen? Ergänze eine der Quellen unten.|¿Quieres ayudar a Attention a reconocer lo que ya conoces? Añade una de estas fuentes.|Vous voulez aider Attention à reconnaître ce que vous connaissez déjà ? Ajoutez une source ci-dessous.|Vuoi aiutare Attention a riconoscere ciò che conosci già? Aggiungi una delle fonti qui sotto.|想帮助 Attention 更好地识别你已熟悉的内容？可添加以下任一来源。|هل تريد مساعدة Attention على معرفة ما تألفه بالفعل؟ أضف أحد المصادر أدناه.|Attention को आपकी परिचित जानकारी पहचानने में मदद करना चाहते हैं? नीचे से कोई स्रोत जोड़ें।
Это необязательно. Всё можно пропустить и подключить позже в настройках профиля.|This is optional. Skip everything now and add sources later in your profile settings.|Alles freiwillig. Du kannst alles überspringen und später in den Profileinstellungen ergänzen.|Es opcional. Puedes omitirlo todo y añadir fuentes más tarde en los ajustes del perfil.|Tout est facultatif. Vous pouvez passer cette étape et ajouter des sources plus tard dans les réglages du profil.|È tutto facoltativo. Puoi saltare questo passaggio e aggiungere fonti dopo, nelle impostazioni del profilo.|这些都不是必需的。可以全部跳过，以后再到资料设置中添加。|كل ذلك اختياري. يمكنك التخطي الآن وإضافة المصادر لاحقًا من إعدادات ملفك.|यह वैकल्पिक है। अभी सब छोड़ सकते हैं और बाद में प्रोफ़ाइल सेटिंग में स्रोत जोड़ सकते हैं।
Уже сохраняете цитаты в Readwise? Attention сможет учитывать их и ваши заметки.|Already save highlights in Readwise? Attention can take them and your notes into account.|Speicherst du Markierungen in Readwise? Attention kann sie und deine Notizen berücksichtigen.|¿Guardas citas en Readwise? Attention puede tenerlas en cuenta junto con tus notas.|Vous enregistrez des passages dans Readwise ? Attention peut en tenir compte, ainsi que de vos notes.|Salvi già citazioni in Readwise? Attention può tenerne conto insieme alle tue note.|已经在 Readwise 中保存摘录？Attention 可以参考这些摘录和你的笔记。|هل تحفظ اقتباسات في Readwise؟ يمكن لـ Attention مراعاتها مع ملاحظاتك.|Readwise में अंश सहेजते हैं? Attention उन्हें और आपके नोट्स को ध्यान में रख सकता है।
Ваши заметки помогут замечать знакомые идеи. Вы сами выберете папку с заметками.|Your notes can help identify familiar ideas. You choose which notes folder to use.|Deine Notizen helfen, vertraute Ideen zu erkennen. Du wählst selbst den Notizordner aus.|Tus notas ayudan a reconocer ideas conocidas. Tú eliges la carpeta de notas.|Vos notes aident à reconnaître les idées familières. Vous choisissez le dossier à utiliser.|Le tue note aiutano a riconoscere idee familiari. Scegli tu la cartella da usare.|你的笔记可帮助识别熟悉的观点。由你选择要使用的笔记文件夹。|تساعد ملاحظاتك على تمييز الأفكار المألوفة. أنت تختار مجلد الملاحظات.|आपके नोट्स परिचित विचार पहचानने में मदद करते हैं। नोट्स का फ़ोल्डर आप चुनेंगे।
История браузера|Browser history|Browserverlauf|Historial del navegador|Historique du navigateur|Cronologia del browser|浏览历史|سجل التصفح|ब्राउज़र इतिहास
Поможет узнавать страницы, которые вы уже открывали. Вы выберете период и разрешите доступ отдельно.|Helps recognise pages you’ve visited. You choose a time period and grant access separately.|Hilft, bereits besuchte Seiten zu erkennen. Du wählst einen Zeitraum und erlaubst den Zugriff separat.|Ayuda a reconocer páginas visitadas. Tú eliges el periodo y autorizas el acceso por separado.|Aide à reconnaître les pages déjà visitées. Vous choisissez la période et autorisez l’accès séparément.|Aiuta a riconoscere pagine già visitate. Scegli il periodo e autorizzi l’accesso separatamente.|帮助识别你已访问的页面。你将选择时间范围，并单独授权访问。|يساعد على تمييز الصفحات التي زرتها. تختار الفترة وتمنح الإذن بشكل منفصل.|पहले खोले गए पेज पहचानने में मदद करता है। समय सीमा आप चुनेंगे और पहुँच की अनुमति अलग से देंगे।
Подключить Readwise|Connect Readwise|Readwise verbinden|Conectar Readwise|Connecter Readwise|Collega Readwise|连接 Readwise|ربط Readwise|Readwise कनेक्ट करें
Выбрать заметки|Choose notes|Notizen auswählen|Elegir notas|Choisir les notes|Scegli le note|选择笔记|اختر الملاحظات|नोट्स चुनें
Выбрать период|Choose a time period|Zeitraum auswählen|Elegir periodo|Choisir la période|Scegli il periodo|选择时间范围|اختر الفترة|समय सीमा चुनें
Добавлено|Added|Hinzugefügt|Añadido|Ajouté|Aggiunto|已添加|تمت الإضافة|जोड़ दिया गया
Не добавлено|Not added|Nicht hinzugefügt|Sin añadir|Non ajouté|Non aggiunto|未添加|لم يُضف|अभी नहीं जोड़ा
Настроить|Manage|Verwalten|Gestionar|Gérer|Gestisci|管理|إدارة|प्रबंधित करें
Пропустить и начать|Skip and start|Überspringen und starten|Omitir y empezar|Passer et commencer|Salta e inizia|跳过并开始|تخطَّ وابدأ|छोड़ें और शुरू करें
Не удалось открыть подключение. Можно пропустить этот шаг и вернуться к нему позже.|Couldn’t load this connection. You can skip this step and come back later.|Die Verbindung konnte nicht geladen werden. Du kannst diesen Schritt überspringen und später zurückkommen.|No se pudo cargar la conexión. Puedes omitir este paso y volver más tarde.|La connexion n’a pas pu être chargée. Vous pouvez passer cette étape et revenir plus tard.|Impossibile caricare il collegamento. Puoi saltare questo passaggio e tornare più tardi.|无法加载此连接。可以跳过此步骤，以后再试。|تعذر تحميل الاتصال. يمكنك تخطي هذه الخطوة والعودة لاحقًا.|कनेक्शन लोड नहीं हुआ। यह चरण छोड़कर बाद में लौट सकते हैं।
`;
