// Interface copy only. Same nine-language column order as profile.ts.
export const OPTIONAL_AI_ROWS = `
Пропустить этот шаг|Skip this step|Diesen Schritt überspringen|Omitir este paso|Passer cette étape|Salta questo passaggio|跳过此步骤|تخطَّ هذه الخطوة|यह चरण छोड़ें
Хотите оценивать статьи с AI?|Want AI to help assess articles?|Möchtest du Artikel mit KI einschätzen?|¿Quieres evaluar artículos con IA?|Évaluer les articles avec l’IA ?|Vuoi valutare gli articoli con l’AI?|想用 AI 评估文章吗？|هل تريد تقييم المقالات بالذكاء الاصطناعي؟|क्या AI से लेखों का आकलन करना चाहेंगे?
AI сопоставляет смысл статьи с вашими целями и помогает находить полезные фрагменты.|AI compares what an article says with your goals and helps find useful passages.|KI gleicht den Inhalt eines Artikels mit deinen Zielen ab und hilft, nützliche Textstellen zu finden.|La IA compara el contenido del artículo con tus objetivos y ayuda a encontrar pasajes útiles.|L’IA rapproche le contenu de l’article de vos objectifs et aide à trouver des passages utiles.|L’AI confronta il contenuto dell’articolo con i tuoi obiettivi e aiuta a trovare passaggi utili.|AI 将文章内容与你的目标进行比较，帮助找到有用的片段。|يقارن الذكاء الاصطناعي مضمون المقال بأهدافك ويساعد في العثور على مقاطع مفيدة.|AI लेख की बातों को आपके लक्ष्यों से मिलाता है और उपयोगी अंश खोजने में मदद करता है।
Это необязательно. Без ключа Attention работает локально. Подключить AI можно позже в настройках.|This is optional. Attention works locally without a key. You can connect AI later in Settings.|Das ist freiwillig. Ohne Schlüssel arbeitet Attention lokal. Du kannst KI später in den Einstellungen verbinden.|Es opcional. Attention funciona localmente sin una clave. Puedes conectar la IA más tarde en Ajustes.|C’est facultatif. Attention fonctionne localement sans clé. Vous pourrez connecter l’IA plus tard dans les réglages.|È facoltativo. Attention funziona localmente senza chiave. Puoi collegare l’AI più tardi nelle impostazioni.|此步骤可选。没有密钥，Attention 仍可在本地运行。以后可在设置中连接 AI。|هذه الخطوة اختيارية. يعمل Attention محليًا دون مفتاح. يمكنك ربط الذكاء الاصطناعي لاحقًا في الإعدادات.|यह वैकल्पिक है। बिना कुंजी के Attention स्थानीय रूप से काम करता है। आप बाद में सेटिंग में AI जोड़ सकते हैं।
1. Создайте ключ в Vercel|1. Create a key in Vercel|1. Erstelle einen Schlüssel bei Vercel|1. Crea una clave en Vercel|1. Créez une clé dans Vercel|1. Crea una chiave in Vercel|1. 在 Vercel 中创建密钥|1. أنشئ مفتاحًا في Vercel|1. Vercel में कुंजी बनाएँ
Войдите или зарегистрируйтесь, нажмите Create key и скопируйте ключ. Затем вернитесь сюда.|Sign in or create an account, choose Create key and copy the key. Then come back here.|Melde dich an oder registriere dich, wähle Create key und kopiere den Schlüssel. Kehre dann hierher zurück.|Inicia sesión o regístrate, elige Create key y copia la clave. Después vuelve aquí.|Connectez-vous ou inscrivez-vous, choisissez Create key et copiez la clé. Puis revenez ici.|Accedi o registrati, scegli Create key e copia la chiave. Poi torna qui.|登录或注册，点击 Create key 并复制密钥，然后返回这里。|سجّل الدخول أو أنشئ حسابًا، واختر Create key وانسخ المفتاح. ثم عد إلى هنا.|साइन इन करें या खाता बनाएँ, Create key चुनें और कुंजी कॉपी करें। फिर यहाँ लौटें।
Создать API-ключ в Vercel ↗|Create an API key in Vercel ↗|API-Schlüssel bei Vercel erstellen ↗|Crear una clave API en Vercel ↗|Créer une clé API dans Vercel ↗|Crea una chiave API in Vercel ↗|在 Vercel 中创建 API 密钥 ↗|إنشاء مفتاح API في Vercel ↗|Vercel में API कुंजी बनाएँ ↗
2. Вставьте API-ключ|2. Paste your API key|2. Füge deinen API-Schlüssel ein|2. Pega tu clave API|2. Collez votre clé API|2. Incolla la chiave API|2. 粘贴 API 密钥|2. الصق مفتاح API|2. अपनी API कुंजी पेस्ट करें
Ключ Vercel AI Gateway|Vercel AI Gateway key|Vercel-AI-Gateway-Schlüssel|Clave de Vercel AI Gateway|Clé Vercel AI Gateway|Chiave Vercel AI Gateway|Vercel AI Gateway 密钥|مفتاح Vercel AI Gateway|Vercel AI Gateway कुंजी
У Vercel свои лимиты и оплата за AI-запросы. Подписка ChatGPT или Claude их не покрывает.|Vercel has its own usage limits and charges for AI requests. A ChatGPT or Claude subscription does not cover them.|Für KI-Anfragen gelten Vercels eigene Nutzungslimits und Kosten. Ein ChatGPT- oder Claude-Abo deckt sie nicht ab.|Vercel tiene sus propios límites y cobros por consultas de IA. Una suscripción a ChatGPT o Claude no los cubre.|Vercel applique ses propres limites et frais aux requêtes IA. Un abonnement ChatGPT ou Claude ne les couvre pas.|Vercel ha limiti e costi propri per le richieste AI. Un abbonamento a ChatGPT o Claude non li copre.|Vercel 有自己的 AI 请求限额和费用，ChatGPT 或 Claude 订阅不包含这些费用。|لـ Vercel حدود استخدام ورسوم خاصة لطلبات الذكاء الاصطناعي. لا يغطيها اشتراك ChatGPT أو Claude.|Vercel की AI अनुरोधों के लिए अपनी सीमाएँ और शुल्क हैं। ChatGPT या Claude की सदस्यता इन्हें शामिल नहीं करती।
При проверке с AI текст статьи и подходящие сведения из профиля отправляются модели через Vercel. Ключ хранится зашифрованным на этом устройстве.|When you check with AI, the article text and relevant profile details are sent to the model through Vercel. Your key is stored encrypted on this device.|Bei einer KI-Prüfung werden der Artikeltext und passende Profilangaben über Vercel an das Modell gesendet. Dein Schlüssel wird verschlüsselt auf diesem Gerät gespeichert.|Al evaluar con IA, el texto del artículo y los datos relevantes del perfil se envían al modelo a través de Vercel. Tu clave se guarda cifrada en este dispositivo.|Lors d’une analyse IA, le texte de l’article et les informations pertinentes du profil sont transmis au modèle via Vercel. Votre clé est chiffrée sur cet appareil.|Durante un’analisi AI, il testo dell’articolo e i dati pertinenti del profilo vengono inviati al modello tramite Vercel. La chiave è salvata in forma cifrata su questo dispositivo.|使用 AI 检查时，文章文本和相关个人资料会通过 Vercel 发送给模型。密钥会加密保存在此设备上。|عند التقييم بالذكاء الاصطناعي، يُرسل نص المقال والمعلومات المناسبة من ملفك إلى النموذج عبر Vercel. يُحفظ مفتاحك مشفرًا على هذا الجهاز.|AI से जाँच के समय लेख का पाठ और प्रोफ़ाइल की संबंधित जानकारी Vercel के माध्यम से मॉडल को भेजी जाती है। कुंजी इस डिवाइस पर एन्क्रिप्ट करके रखी जाती है।
Подключить и продолжить|Connect and continue|Verbinden und weiter|Conectar y continuar|Connecter et continuer|Collega e continua|连接并继续|اربط وتابع|कनेक्ट करें और आगे बढ़ें
Пока без AI|Continue without AI|Vorerst ohne KI|Continuar sin IA|Continuer sans IA|Continua senza AI|暂不使用 AI|المتابعة دون ذكاء اصطناعي|अभी AI के बिना जारी रखें
Продолжить с текущими настройками|Keep current settings|Aktuelle Einstellungen beibehalten|Mantener la configuración actual|Garder les réglages actuels|Mantieni le impostazioni attuali|保留当前设置|المتابعة بالإعدادات الحالية|मौजूदा सेटिंग के साथ जारी रखें
Ключ уже сохранён. Можно оставить его или вставить другой.|A key is already saved. You can keep it or paste a different one.|Ein Schlüssel ist bereits gespeichert. Du kannst ihn behalten oder einen anderen einfügen.|Ya hay una clave guardada. Puedes conservarla o pegar otra.|Une clé est déjà enregistrée. Vous pouvez la garder ou en coller une autre.|Una chiave è già salvata. Puoi tenerla o incollarne un’altra.|已保存密钥。你可以保留它，也可以粘贴另一把密钥。|يوجد مفتاح محفوظ بالفعل. يمكنك الاحتفاظ به أو لصق مفتاح آخر.|एक कुंजी पहले से सहेजी है। उसे रख सकते हैं या दूसरी पेस्ट कर सकते हैं।
Не удалось загрузить настройки AI. Этот шаг можно пропустить.|Couldn’t load AI settings. You can skip this step.|Die KI-Einstellungen konnten nicht geladen werden. Du kannst diesen Schritt überspringen.|No se pudo cargar la configuración de IA. Puedes omitir este paso.|Impossible de charger les réglages IA. Vous pouvez passer cette étape.|Impossibile caricare le impostazioni AI. Puoi saltare questo passaggio.|无法加载 AI 设置。你可以跳过此步骤。|تعذر تحميل إعدادات الذكاء الاصطناعي. يمكنك تخطي هذه الخطوة.|AI सेटिंग लोड नहीं हुईं। यह चरण छोड़ सकते हैं।
Скопируйте API-ключ целиком из Vercel или пропустите этот шаг.|Copy the full API key from Vercel, or skip this step.|Kopiere den vollständigen API-Schlüssel aus Vercel oder überspringe diesen Schritt.|Copia la clave API completa de Vercel u omite este paso.|Copiez la clé API complète depuis Vercel ou passez cette étape.|Copia la chiave API completa da Vercel oppure salta questo passaggio.|请从 Vercel 复制完整的 API 密钥，或跳过此步骤。|انسخ مفتاح API كاملًا من Vercel، أو تخطَّ هذه الخطوة.|Vercel से पूरी API कुंजी कॉपी करें या यह चरण छोड़ें।
Не удалось сохранить настройки. Попробуйте ещё раз или пропустите этот шаг.|Couldn’t save the settings. Try again or skip this step.|Die Einstellungen konnten nicht gespeichert werden. Versuche es erneut oder überspringe diesen Schritt.|No se pudo guardar la configuración. Reinténtalo u omite este paso.|Impossible d’enregistrer les réglages. Réessayez ou passez cette étape.|Impossibile salvare le impostazioni. Riprova o salta questo passaggio.|无法保存设置。请重试或跳过此步骤。|تعذر حفظ الإعدادات. حاول مجددًا أو تخطَّ هذه الخطوة.|सेटिंग सहेजी नहीं जा सकीं। फिर कोशिश करें या यह चरण छोड़ें।
`;
