/**
 * A deliberately small cross-language concept layer. These are not profile
 * translations: they only let equivalent high-level topics meet in local
 * matching and connector indices when their surface language differs.
 */
const CONCEPT_ALIASES = {
  ai: [
    'ai',
    'artificial intelligence',
    'machine intelligence',
    'llm',
    'large language model',
    'artificial general intelligence',
    'agi',
    'искусственный интеллект',
    'ии',
    'большая языковая модель',
    'künstliche intelligenz',
    'inteligencia artificial',
    'intelligenza artificiale',
    'intelligence artificielle',
    '人工智能',
    '人工智慧',
    'الذكاء الاصطناعي',
    'कृत्रिम बुद्धिमत्ता',
  ],
  machine_learning: [
    'machine learning',
    'ml',
    'deep learning',
    'neural network',
    'машинное обучение',
    'глубокое обучение',
    'нейронная сеть',
    'maschinelles lernen',
    'aprendizaje automático',
    'aprendizaje profundo',
    'apprendimento automatico',
    'apprentissage automatique',
    '机器学习',
    '機器學習',
    'تعلم الآلة',
    'التعلم الآلي',
    'मशीन लर्निंग',
  ],
  software_engineering: [
    'software engineering',
    'software development',
    'programming',
    'coding',
    'разработка программного обеспечения',
    'разработка по',
    'программирование',
    'softwareentwicklung',
    'ingeniería de software',
    'sviluppo software',
    'génie logiciel',
    'développement logiciel',
    '软件工程',
    '軟體工程',
    'هندسة البرمجيات',
    'सॉफ्टवेयर इंजीनियरिंग',
  ],
  data_science: [
    'data science',
    'data analysis',
    'analytics',
    'наука о данных',
    'анализ данных',
    'datenwissenschaft',
    'datenanalyse',
    'ciencia de datos',
    'análisis de datos',
    'scienza dei dati',
    'science des données',
    '数据科学',
    '資料科學',
    'علم البيانات',
    'डेटा साइंस',
  ],
  research: [
    'research',
    'scientific study',
    'academic paper',
    'исследование',
    'научная статья',
    'forschung',
    'wissenschaftliche studie',
    'investigación',
    'studio scientifico',
    'recherche',
    'étude scientifique',
    '研究',
    '科学研究',
    'بحث علمي',
    'अनुसंधान',
    'शोध',
  ],
  economics: [
    'economics',
    'economy',
    'macroeconomics',
    'microeconomics',
    'экономика',
    'макроэкономика',
    'wirtschaft',
    'ökonomie',
    'economía',
    'economia',
    'économie',
    '经济学',
    '經濟學',
    'اقتصاد',
    'अर्थशास्त्र',
  ],
  finance: [
    'finance',
    'investing',
    'investment',
    'финансы',
    'инвестиции',
    'finanzen',
    'investieren',
    'finanzas',
    'inversión',
    'finanza',
    'investimenti',
    'finances',
    'investissement',
    '金融',
    '投资',
    '投資',
    'تمويل',
    'استثمار',
    'वित्त',
    'निवेश',
  ],
  psychology: [
    'psychology',
    'behavioral science',
    'психология',
    'поведенческая наука',
    'psychologie',
    'psicología',
    'psicologia',
    '心理学',
    '心理學',
    'علم النفس',
    'मनोविज्ञान',
  ],
  philosophy: [
    'philosophy',
    'философия',
    'philosophie',
    'filosofía',
    'filosofia',
    '哲学',
    '哲學',
    'فلسفة',
    'दर्शन',
  ],
  history: [
    'history',
    'historical',
    'история',
    'исторический',
    'geschichte',
    'historia',
    'storia',
    'histoire',
    '历史',
    '歷史',
    'تاريخ',
    'इतिहास',
  ],
  politics: [
    'politics',
    'public policy',
    'geopolitics',
    'политика',
    'государственная политика',
    'politik',
    'política',
    'politica',
    'politique',
    '政治',
    'السياسة',
    'राजनीति',
  ],
  productivity: [
    'productivity',
    'time management',
    'personal effectiveness',
    'продуктивность',
    'управление временем',
    'produktivität',
    'productividad',
    'produttività',
    'productivité',
    '生产力',
    '生產力',
    'الإنتاجية',
    'उत्पादकता',
  ],
  career: [
    'career',
    'job search',
    'professional development',
    'карьера',
    'поиск работы',
    'beruf',
    'karriere',
    'carrera profesional',
    'carriera',
    'carrière',
    '职业发展',
    '職業發展',
    'المسار المهني',
    'करियर',
  ],
  education: [
    'education',
    'learning',
    'teaching',
    'образование',
    'обучение',
    'bildung',
    'lernen',
    'educación',
    'aprendizaje',
    'istruzione',
    'apprendimento',
    'éducation',
    'apprentissage',
    '教育',
    '学习',
    'التعليم',
    'التعلم',
    'शिक्षा',
    'सीखना',
  ],
  german_language: [
    'german',
    'german language',
    'deutsch',
    'deutsche',
    'deutscher',
    'deutsches',
    'deutschen',
    'deutsche sprache',
    'немецкий язык',
    'немецкого языка',
    'alemán',
    'idioma alemán',
    'tedesco',
    'lingua tedesca',
    'allemand',
    'langue allemande',
    '德语',
    '德語',
    'الألمانية',
    'जर्मन',
  ],
  health: [
    'health',
    'medicine',
    'wellbeing',
    'здоровье',
    'медицина',
    'gesundheit',
    'medizin',
    'salud',
    'medicina',
    'santé',
    'médecine',
    '健康',
    '医学',
    'الصحة',
    'الطب',
    'स्वास्थ्य',
    'चिकित्सा',
  ],
  climate: [
    'climate',
    'climate change',
    'sustainability',
    'климат',
    'изменение климата',
    'устойчивое развитие',
    'klima',
    'klimawandel',
    'cambio climático',
    'cambiamento climatico',
    'changement climatique',
    '气候变化',
    '氣候變化',
    'تغير المناخ',
    'जलवायु परिवर्तन',
  ],
  security: [
    'cybersecurity',
    'information security',
    'privacy',
    'кибербезопасность',
    'информационная безопасность',
    'приватность',
    'cybersicherheit',
    'datenschutz',
    'ciberseguridad',
    'privacidad',
    'sicurezza informatica',
    'cybersécurité',
    '网络安全',
    '網路安全',
    'الأمن السيبراني',
    'साइबर सुरक्षा',
  ],
} as const;

function normalizedText(value: string): string {
  return value
    .normalize('NFKC')
    .toLocaleLowerCase()
    .replace(/[\p{P}\p{S}]+/gu, ' ')
    .replace(/\s+/gu, ' ')
    .trim();
}

function includesAlias(
  normalized: string,
  lexicalTokens: Set<string>,
  alias: string,
): boolean {
  const candidate = normalizedText(alias);
  if (!candidate) return false;
  if (!candidate.includes(' ') && !/[\u3400-\u9fff]/u.test(candidate)) {
    return lexicalTokens.has(candidate);
  }
  if (/[\u3400-\u9fff]/u.test(candidate)) return normalized.includes(candidate);
  return ` ${normalized} `.includes(` ${candidate} `);
}

export function conceptTokens(
  value: string,
  lexicalTokens: Set<string>,
): Set<string> {
  const normalized = normalizedText(value);
  const concepts = new Set<string>();
  for (const [concept, aliases] of Object.entries(CONCEPT_ALIASES)) {
    if (
      aliases.some((alias) => includesAlias(normalized, lexicalTokens, alias))
    ) {
      concepts.add(`concept:${concept}`);
    }
  }
  return concepts;
}
